### ISSUE TITLE
Status of this fork vs DavidKinder repo

### ISSUE THREAD

**Issue by akien-mga** [erkyrath/inform6#2]
Hello,

I'm currently looking at packaging Inform6 for Mageia now that the licensing information has been cleared out.
I see that you have many commits that are not in @DavidKinder's repository, and thus I would like some information as to which repository should be considered as the one for upstream development. If it's @DavidKinder's, are your commits destined to be merged upstream at some time, or do they serve another purpose?

Thanks in advance.

**Comment by erkyrath** [comment]
Treat this as a dev fork of @DavidKinder's. There's only one commit in erkyrath/master which is not in DavidKinder/master; that is a bug fix which will be merged up in due course.

**Comment by akien-mga** [comment]
Thanks for the explanation :) I was mislead by the number of commits on the two repos, but hadn't looked into the details.

**Comment by akien-mga** [comment]
If I understand correctly, you make developments in this fork, and then @DavidKinder cherry-picks them manually for the official repo?

I don't mean to change your workflow, but have you considered using the nice facilities offered by pull requests? You'd just have to redo your fork by actually forking @DavidKinder's repo via the GitHub interface, and then make a pull request of your changes to the main upstream branch for @DavidKinder to review, comment on, and eventually merge once it has been considered good enough. The main advantages are the traceability of the changes, peer review, and also the fact that the commits will be properly attributed to you, instead of relying on @DavidKinder mentioning you in the commit log every time.

**Comment by erkyrath** [comment]
*If I understand correctly, you make developments in this fork, and then @DavidKinder cherry-picks them manually for the official repo?*

Yes. This setup works for us.
